version: '3.4'

services:
  iiot.messagebroker:
    image: ${DOCKER_REGISTRY-}iiotmessagebroker
    build:
      context: .
      dockerfile: IIOT.MessageBroker/Dockerfile
    ports:
        - "1844:1844"  
    networks:
        - webproxy
  
  iiot.simulator:
    image: ${DOCKER_REGISTRY-}iiotsimulator
    environment:
        - ASPNETCORE_ENVIRONMENT=docker
    build:
      context: .
      dockerfile: IIOT.Simulator/Dockerfile
    depends_on: 
        - iiot.messagebroker
    networks:
        - webproxy

  iiot.api:
    image: ${DOCKER_REGISTRY-}iiotapi
    build:
      context: .
      dockerfile: IIOT.API/Dockerfile
    networks:
        - webproxy
    ports:
        - "5000:5000"     

networks:
  webproxy:
    driver: bridge


