version: "3.4"
services:
  iiot.simulator:

  iiot.messagebroker:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  iiot.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

